version: '3'
services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    links:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
    command: "/bin/sh"
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ttt@t.t"
      PGADMIN_DEFAULT_PASSWORD: "ttt"
    ports:
      - 7778:80
    links:
      - db
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
